"""init

Revision ID: 56fc73f7392c
Revises: e8e65c8776fc
Create Date: 2022-07-10 07:44:07.004661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fc73f7392c'
down_revision = 'e8e65c8776fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'text')
    # ### end Alembic commands ###
