"""init

Revision ID: 76a3dbda9d6f
Revises: b5808345bb99
Create Date: 2022-07-10 06:47:11.797051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a3dbda9d6f'
down_revision = 'b5808345bb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'time_created')
    # ### end Alembic commands ###
